server:
  port: 9100
spring:
  application:
    # 微服务名称
    name: lg-service-page
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 123456
eureka:
  client:
    # eureka server的路径
    service-url:
      defaultZone: http://127.0.0.1:9200/eureka/
  instance:
    #使用ip注册，否则会使用主机名注册了（此处考虑到对老版本的兼容，新版本经过实验都是ip）
    prefer-ip-address: true
    #自定义实例显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress
    instance-id: ${spring.cloud.client.ip- address}:${spring.application.name}:${server.port}:@project.version@